version: "3"

services:
  geth:
    image: ethereum/client-go:stable
    pull_policy: always
    container_name: gethnode
    restart: unless-stopped
    networks:
      - ethereum
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
    volumes:
      - /data/geth:/root/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 1m
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    command:
      - --http
      - --http.api
      - "eth,web3,net,debug,txpool"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3"
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      # - --txpool.accountslots=16
      # --txpool.globalqueue=1024
      # - --txpool.globalslots=10000
      # - --txpool.lifetime=3h0m0s
      - --cache=8192
      # - --maxpeers=100
      # Blockchain sync mode ("snap", "full", or "light")
      - --syncmode=full
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      # - --gcmode=full
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts="*"
      - --authrpc.jwtsecret=/root/.ethereum/geth/jwtsecret
  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    pull_policy: always
    container_name: beacon-node
    restart: unless-stopped
    networks:
      - ethereum
    ports:
      - "3500:3500"
      - "4000:4000"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - /data/prysm:/data
      - /data/geth:/data_geth
    stop_signal: SIGINT
    stop_grace_period: 1m
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --jwt-secret=/data_geth/geth/jwtsecret
      - --execution-endpoint=http://geth:8551
      - --checkpoint-sync-url=https://sync.invis.tools
      - --genesis-beacon-api-url=https://sync.invis.tools

networks:
  ethereum:

